# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c90327d3a3673c93c0e58fc127d2a1ac16e8bae06d30d568b967292b6067de80c15df123c9cd99ad43fb1dcefac7f1c2df1096c68313dcf6e4080f8fcec55542

test:
  secret_key_base: 4374f8f8ddfacd5434550824911f6030aef818803409d6b9de84724c8629ff729a8c5852b2dc8d31edcbb49e057c19a090513de608ed0cca25601d4b6f9ca382

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
